# Generated by Django 5.2.6 on 2025-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
