# Generated by Django 5.2.6 on 2025-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0002_alter_requestlog_city_alter_requestlog_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.TextField()),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
