
services:
  django:
    build: .
    container_name: django_app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend
    entrypoint: ["/app/entrypoint.sh"] 
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build: .
    container_name: celery_worker
    working_dir: /app
    command: celery -A django_celery_ip_tracker worker -l info -P solo
    depends_on:
      - django
      - redis
    env_file:
      - .env
    networks:
      - backend

  celery_beat:
    build: .
    container_name: celery_beat
    working_dir: /app
    command: celery -A django_celery_ip_tracker beat -l info
    depends_on:
      - django
      - redis
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_django
    ports:
      - "6379:6379"
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: database
    # volumes:
    #   - mysql_data:/var/lib/mysql
    env_file: 
      - .env
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
